name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global init.defaultBranch master

      - name: Setup build environment
        run: ./panda setup

      - name: Apply patches
        run: ./panda patch

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build paperclipJar
          read-only: false

      - name: Paperclip
        run: |
          ./panda paperclip
          mv -v "./paperclip.jar" "./pandaspigot-$GITHUB_RUN_NUMBER.jar"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Server JAR
          path: pandaspigot-${{ github.run_number }}.jar
